export const FETCH_TEMPERATURE_REQUEST = "FETCH_TEMPERATURE_REQUEST";
export const FETCH_TEMPERATURE_SUCCESS = "FETCH_TEMPERATURE_SUCCESS";
export const FETCH_TEMPERATURE_FAILURE = "FETCH_TEMPERATURE_FAILURE";
